# Generated by Django 3.0.6 on 2020-06-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200622_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(default=1, verbose_name=(('0', 'Text'), ('1', 'Yes/No'), ('2', 'Multichoice'))),
            preserve_default=False,
        ),
    ]
