# Generated by Django 3.0.6 on 2020-06-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200623_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yesnoquestion',
            options={'verbose_name': 'YesNoQuestion'},
        ),
        migrations.RemoveField(
            model_name='yesnoquestion',
            name='yes_no',
        ),
    ]
